INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWOR)
VALUES (1, 'abcd1@gmail.com', 'abcd1', '1234567', 'abc');

INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWOR)
VALUES (2, 'abcd2@gmail.com', 'abcd2', '1234568', 'def');